
python ./save_features8.py --dataset oc_clipart --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_clipart --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/clipart/checkpoints/resnet18_vision-epoch130-acc63.483.pth
python ./save_features8.py --dataset oc_painting --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_clipart --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/clipart/checkpoints/resnet18_vision-epoch130-acc63.483.pth
python ./save_features8.py --dataset oc_real --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_clipart --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/clipart/checkpoints/resnet18_vision-epoch130-acc63.483.pth
python ./save_features8.py --dataset oc_quickdraw --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_clipart --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/clipart/checkpoints/resnet18_vision-epoch130-acc63.483.pth
python ./save_features8.py --dataset oc_sketch --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_clipart --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/clipart/checkpoints/resnet18_vision-epoch130-acc63.483.pth


python ./save_features8.py --dataset oc_clipart --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_painting --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/painting/checkpoints/resnet18_vision-epoch130-acc48.517.pth
python ./save_features8.py --dataset oc_painting --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_painting --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/painting/checkpoints/resnet18_vision-epoch130-acc48.517.pth
python ./save_features8.py --dataset oc_real --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_painting --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/painting/checkpoints/resnet18_vision-epoch130-acc48.517.pth
python ./save_features8.py --dataset oc_quickdraw --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_painting --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/painting/checkpoints/resnet18_vision-epoch130-acc48.517.pth
python ./save_features8.py --dataset oc_sketch --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_painting --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/painting/checkpoints/resnet18_vision-epoch130-acc48.517.pth


python ./save_features8.py --dataset oc_clipart --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_quickdraw --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/quickdraw/checkpoints/resnet18_vision-epoch130-acc68.286.pth
python ./save_features8.py --dataset oc_painting --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_quickdraw --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/quickdraw/checkpoints/resnet18_vision-epoch130-acc68.286.pth
python ./save_features8.py --dataset oc_real --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_quickdraw --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/quickdraw/checkpoints/resnet18_vision-epoch130-acc68.286.pth
python ./save_features8.py --dataset oc_quickdraw --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_quickdraw --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/quickdraw/checkpoints/resnet18_vision-epoch130-acc68.286.pth
python ./save_features8.py --dataset oc_sketch --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_quickdraw --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/quickdraw/checkpoints/resnet18_vision-epoch130-acc68.286.pth


python ./save_features8.py --dataset oc_clipart --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_real --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/real/checkpoints/resnet18_vision-epoch130-acc66.965.pth
python ./save_features8.py --dataset oc_painting --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_real --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/real/checkpoints/resnet18_vision-epoch130-acc66.965.pth
python ./save_features8.py --dataset oc_real --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_real --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/real/checkpoints/resnet18_vision-epoch130-acc66.965.pth
python ./save_features8.py --dataset oc_quickdraw --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_real --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/real/checkpoints/resnet18_vision-epoch130-acc66.965.pth
python ./save_features8.py --dataset oc_sketch --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_real --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/real/checkpoints/resnet18_vision-epoch130-acc66.965.pth


python ./save_features8.py --dataset oc_clipart --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_sketch --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/sketch/checkpoints/resnet18_vision-epoch130-acc52.572.pth
python ./save_features8.py --dataset oc_painting --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_sketch --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/sketch/checkpoints/resnet18_vision-epoch130-acc52.572.pth
python ./save_features8.py --dataset oc_real --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_sketch --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/sketch/checkpoints/resnet18_vision-epoch130-acc52.572.pth
python ./save_features8.py --dataset oc_quickdraw --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_sketch --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/sketch/checkpoints/resnet18_vision-epoch130-acc52.572.pth
python ./save_features8.py --dataset oc_sketch --model visionresnet18 --method protonet --train_aug  --n_shot 1 --savename pre_sketch --tweights /home/suh/deeplearning/pytrain_config/pycifar/classification_training/domainnet_resnet18_pretrained/sketch/checkpoints/resnet18_vision-epoch130-acc52.572.pth

